Error404/Error404/Models/SaleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Error404.Model.Model;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Error404.Models
{
    public class SaleViewModel
    {
        public SaleViewModel()
        {
            SaleDetials = new List<SaleDetails>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public DateTime Date { get; set; }
        public float GrandTotal { get; set; }
        public float Discount { get; set; }
        public float DiscountAmount { get; set; }
        public float PayableAmount { get; set; }
        public double LoyalityPoint { get; set; }
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }
        public List<SaleDetails> SaleDetials { get; set; }
        public List<SelectListItem> CustomerSelectListItems { get; set; }
        public List<Sale> Sales { get; set; }
    }
}

Error404/Error404/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Routing.Constraints;
using Error404.BLL.BLL;
using Error404.Model.Model;
using Error404.Repository.Repository;
using Error404.Models;
using AutoMapper;


namespace Error404.Controllers
{
    public class SalesController : Controller
    {

        CategoryManager _categoryManager = new CategoryManager();
        ProductManager _productManager = new ProductManager();
        SalesManager _salesManager = new SalesManager();
        CustomerManager _customerManager = new CustomerManager();
        PurchaseManager _purchaseManager = new PurchaseManager();
        PurchaseQtyManager _purchaseQtyManager = new PurchaseQtyManager();



        public ActionResult Index()
        {
            SaleViewModel saleViewModel = new SaleViewModel();
            saleViewModel.Sales = _salesManager.GetAll();
            return View(saleViewModel);
        }
        public ActionResult AddSales()
        {
            SaleDetailsViewModel saleDetialsViewModel = new SaleDetailsViewModel();
            SaleViewModel saleViewModel = new SaleViewModel();

            saleViewModel.CustomerSelectListItems = _customerManager
                .GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();


            saleDetialsViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            ViewBag.CategoryId = saleDetialsViewModel.CategorySelectListItems;
            saleViewModel.Sales = _salesManager.GetAll();

            return View(saleViewModel);
        }
        [HttpPost]
        public ActionResult AddSales(SaleViewModel saleViewModel)
        {
            SaleDetailsViewModel saleDetialsViewModel = new SaleDetailsViewModel();
            string message = "";
            if (ModelState.IsValid)
            {
                var resetLoyaltyPoint = saleViewModel.LoyalityPoint - (saleViewModel.LoyalityPoint / 10);
                var newLoyaltyPoint = Convert.ToInt16(resetLoyaltyPoint + ((saleViewModel.GrandTotal) / 1000));
                var customer = _customerManager.GetById(saleViewModel.CustomerId);
                customer.Loyality = newLoyaltyPoint;
                _customerManager.Update(customer);


                Sale sale = Mapper.Map<Sale>(saleViewModel);
                _salesManager.Add(sale);
            }
            else
            {
                message = "modelstate is invalid";
            }


            saleViewModel.CustomerSelectListItems = _customerManager
                                                        .GetAll()
                                                        .Select(c => new SelectListItem()
                                                        {
                                                            Value = c.Id.ToString(),
                                                            Text = c.Name
                                                        }).ToList();

            saleDetialsViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            ViewBag.CategoryId = saleDetialsViewModel.CategorySelectListItems;
            saleViewModel.Sales = _salesManager.GetAll();
            return View(saleViewModel);
        }
        public JsonResult GetProductByCategoryId(int? categoryId)
        {
            var productList = _productManager.GetAll().Where(c => c.CategoryId == categoryId);
            var products = from p in productList select (new { p.Id, p.Name });
            return Json(products, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetAvlQuntyByProduct(int? productId)
        {
            var purchsaeList = _purchaseManager.GetAll().OrderByDescending(c => c.ProductId == productId).ToList().FirstOrDefault();
            //var purchsaeList = _purchaseReportManager.GetAvailableQtyByProductIdFrmPurchase(productId);
            return Json(purchsaeList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetLoyalityPointByCustomer(int? customerId)
        {
            var customerlist = _customerManager.GetAll().OrderByDescending(c => c.Id == customerId).ToList().FirstOrDefault();

            return Json(customerlist, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetMRPByPurchaseDetials(int? customerId)
        {
            var customerlist = _customerManager.GetAll().OrderByDescending(c => c.Id == customerId).ToList().FirstOrDefault();

            return Json(customerlist, JsonRequestBehavior.AllowGet);
        }


        //public JsonResult GetAvailableQtyByProductIdFrmPurchase(int productId)
        //{
        //    var getAvailableProduct = _purchaseReportManager.GetAvailableQtyByProductIdFrmPurchase(productId);
        //    //var getSaleAvailableProduct = _purchaseReportManager.GetSaleAvailableProduct(productId);

        //    //if (getSaleAvailableProduct > 0)
        //    //{
        //    //    getAvailableProduct = getAvailableProduct - getSaleAvailableProduct;
        //    //}

        //    return Json(getAvailableProduct, JsonRequestBehavior.AllowGet);
        //}

        public JsonResult GetAvailableQtyByProductId(int productId)
        {
            var getAvailableProduct = _purchaseQtyManager.GetAvailableProduct(productId);
            var getSaleAvailableProduct = _purchaseQtyManager.GetSaleAvailableProduct(productId);

            if (getSaleAvailableProduct > 0)
            {
                getAvailableProduct = getAvailableProduct - getSaleAvailableProduct;
            }

            return Json(getAvailableProduct, JsonRequestBehavior.AllowGet);
        }



        public ActionResult CustomerDetails()
        {
            SaleViewModel saleViewModel = new SaleViewModel();
            saleViewModel.Sales = _salesManager.GetAll();
            return View(saleViewModel);
        }
        // Sales Detials
        public ActionResult SalesDetails(int id)
        {
            //PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            SaleViewModel saleViewModel = new SaleViewModel();

            //purchaseViewModel.Purchases = _purchaseManager.GetAllPurchase().Where(c => c.Id == id).ToList();
            saleViewModel.Sales = _salesManager.GetAll().Where(c => c.Id == id).ToList();
            ViewBag.Category = _categoryManager.GetAll();

            PurchaseDetailsViewModel purchaseDetailsViewModel = new PurchaseDetailsViewModel();
            SaleDetailsViewModel saleDetialsViewModel = new SaleDetailsViewModel();

            //purchaseDetailsViewModel.PurchaseDetails = _purchaseManager.GetAll().Where(c => c.PurchaseId == id).ToList();
            saleDetialsViewModel.SaleDetails = _salesManager.GetAllSaleDetails().Where(c => c.SaleId == id).ToList();
            ViewBag.Details = saleDetialsViewModel.SaleDetails;
            return View(saleViewModel);
        }

        public JsonResult SearchCustomer(string SearchData)
        {
            List<Sale> customers = _salesManager.GetAllSale();
            var date = customers.Where(c => c.Date.ToString().Contains(SearchData)).ToList();
            var name = customers.Where(c => c.Customer.Name.Contains(SearchData)).ToList();          
            if (date.Count() != 0)
            {
                return Json(date, JsonRequestBehavior.AllowGet);
            }

            if (name.Count() != 0)
            {
                return Json(name, JsonRequestBehavior.AllowGet);
            }
           
            return Json(null, JsonRequestBehavior.AllowGet);
        }


    }
}

Error404/Error404/Views/Sales/Index.cshtml
@model Error404.Models.SaleViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container pb-5">
    <h2 class="text-center">Sales Details</h2>
    <br /><br />
    <div class="form-inline my-4">
        <input class="form-control" type="text" name="Search" id="Search" placeholder="Search By Supplier Name, Date or Invoice No" style="width: 87%;border: 1px solid #19BDA5;">
        <button id="SearchButton" class="btn btn-success">Search</button>
        <h4 id="required" style="color:red;"></h4>
    </div>
    <br />
    @Html.ActionLink("Add", "AddSales", "Sales", null, new { @class = "btn btn-info" })
    <br /><br />
    <table class="table table-bordered table-hover" id="purchase">
        <thead>
            <tr class="badge-gradient-dark text-white">
                <th>SL</th>
                <th>Customer</th>
                <th>Date</th>
                <th>Loyality Point</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @{
                int sl = 1;
            }
            @foreach (var customer in Model.Sales)
            {
                <tr>
                    <td>@(sl++)</td>
                    <td>@customer.Customer.Name</td>
                    <td>@customer.Date</td>
                    <td>@customer.Customer.Loyality</td>
                    <td>@Html.ActionLink("Details", "SalesDetails", "Sales", new { Id = customer.Id }, new { @class = "btn btn-danger" })</td>
                </tr>
            }

        </tbody>
    </table>
</div>
@section MyScript{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @*For Live Search*@
    <script>
        $(document).ready(function () {
            $("#SearchButton").click(function () {
                if ($("#Search").val() == "") {
                    //alert("required..");
                    $("#required").text("Please Required Search Value");
                    return;
                }
                $("#required").text("");
                SearchTable($("#Search").val());
            });

            function SearchTable(value) {
                $("#purchase tbody tr").each(function () {
                    var found = 'false';
                    $(this).each(function () {
                        if ($(this).text().toLowerCase().indexOf(value.toLowerCase()) > 0) {
                            found = 'true';
                        }
                    });
                    if (found == 'true') {
                        $(this).show();
                    }
                    else {
                        $(this).hide();
                    }

                });
            }
        });
    </script>
}

Error404/Error404/Views/Sales/SalesDetails.cshtml
@model Error404.Models.SaleViewModel
@{
    ViewBag.Title = "PurchaseDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container pb-5" style="width:50%">
    <h2 class="text-center">Customrt Details</h2>
    <br /><br />
    <table class="table table-bordered table-hover">
        <tbody>
            @foreach (var purchase in Model.Sales)
            {
                <tr>
                    <th>Customer</th>
                    <td>@purchase.Customer.Name</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>@purchase.Date</td>
                </tr>
                <tr>
                    <th>LoyalityPoint</th>
                    <td>@purchase.Customer.Loyality</td>
                </tr>
            }

        </tbody>
    </table>
</div>

<div class="container pb-5">
    <h2 class="text-center">Product Details</h2>
    <br /><br />
    <table class="table table-bordered table-hover table-responsive">
        <thead>
            <tr class="badge-gradient-dark text-white">
                <th>Sl</th>
                <th>Category</th>
                <th>Product</th>
                @*<th>Date</th>*@
                <th>GrandTotal</th>
                <th>Discount</th>
                <th>DiscountAmount</th>
                <th>PayableAmount</th>
                <th>Quantity</th>
                <th>AvailableQuantity</th>
                <th>MRP</th>
                <th>TotalMRP</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
                var SaleDetailsViewModel = ViewBag.Details;
            }
            @foreach (var salesList in SaleDetailsViewModel)
            {
                <tr>
                    <td>@(i++)</td>
                    @foreach (var category in ViewBag.Category)
                    {
                        if (category.Id == salesList.CategoryId)
                        {
                            <td>@category.Name</td>
                        }
                    }
                    <td>@salesList.Product.Name</td>
                    @*<td>@salesList.Date</td>*@
                    @*<td>@salesList.</td>*@
                    <td>@salesList.Sale.GrandTotal</td>
                    <td>@salesList.Sale.Discount</td>
                    <td>@salesList.Sale.DiscountAmount</td>
                    <td>@salesList.Sale.PayableAmount</td>
                    <td>@salesList.Quantity</td>
                    <td>@salesList.AvailableQuantity</td>
                    <td>@salesList.MRP</td>
                    <td>@salesList.TotalMRP</td>
                </tr>
            }
        </tbody>
    </table>
</div>